### ISSUE TITLE
Bug declaration ExcelReader::createSheet

### ISSUE THREAD

**Issue by mefutu01** [aVadim483/fast-excel-laravel#2]
Hi I have the latest version of your software "^2.4". Lately I'm starting to get execution errors like this.  

`Declaration of avadim\FastExcelLaravel\ExcelReader::createSheet(string $sheetName, $sheetId, $file, $path): avadim\FastExcelLaravel\SheetReader must be compatible with avadim\FastExcelReader\Excel::createSheet(string $sheetName, $sheetId, $file, $path, $excel): avadim\FastExcelReader\Interfaces\InterfaceSheetReader`

Can you please help with that. The code that breaks here . 

`$file = $request->validate(['import' => 'file|mimes:xls,xlsx']);`
`$productIds = [];`
`$excel = \Excel::open($file['import']);`

**Comment by mefutu01** [comment]
I used 
`$excel = \avadim\FastExcelReader\Excel::open($file['import']);`

That solved my problem.

**Comment by aVadim483** [comment]
thanx for report, fixed
