### ISSUE TITLE
Temp File Location not clearing

### ISSUE THREAD

**Issue by lachlanhickey** [aVadim483/fast-excel-laravel#4]
Great app - has changed my life. 

I noticed the /storage/app/tmp/fast-excel is not clearing temp files even after a successful build. Any ideas?

**Comment by aVadim483** [comment]
Try version 2.7 with new temporary file handler

**Comment by lachlanhickey** [comment]
Thanks for getting back to me so quick. New vers downloaded with new .tmp files. Should i be expecting the files to delete once the file is created?

**Comment by lachlanhickey** [comment]
Ok, disrecard. The files have cleared :)
